name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          repository: MCSMDS/Robot
          token: ${{ secrets.GitHub_PAT }}

      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/setup-ruby@v1.1.2
        with:
          ruby-version: 2.6
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.13

#      - shell: bash
#        env:
#          AUTOLOGIN: ${{ secrets.AUTOLOGIN }}
#        run: |
#          echo "$AUTOLOGIN" > ./mirai/config/Console/AutoLogin.yml

      - name: Run script
        run: |
          cd mirai
          chmod +x ./start-mirai-console.sh
          ./start-mirai-console.sh --no-console &
          cd ../node-mirai
          npm i
          cd ../
          node node-mirai/bot.js

#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
