name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '45 15 * * *'
    - cron: '33 20 * * *'
    - cron: '21 01 * * *'
    - cron: '09 06 * * *'
    - cron: '57 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          repository: MCSMDS/Robot
          token: ${{ secrets.GITHUBPATA }}

      - name: Docker
        run: |
          docker pull node:latest
          docker pull python:latest
          docker pull ruby:latest
          docker pull golang:latest

      - name: Build
        run: |
          chmod +x ./mirai/start-mirai-console.sh
          cd node-mirai
          npm i

      - name: Start
        run: node node-mirai/launch.js ${{ github.event_name }}

#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3



